sudo: required

services:
  - docker

language: go
go:
  - 1.8.3

env:
  global:
    - IMAGE_TAG=$DOCKER_USERNAME/docker-http-server

install:
  - # an empty install saves the hassle of pseudo-getting deps (they're vendored, so no need!)

script:
  - make ci

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE_TAG;
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: http-server
  skip_cleanup: true
  on:
    tags: true
